### ISSUE TITLE
Regra de negócio

### ISSUE THREAD

**Issue by rrenans** [rrenans/Union#2]
## Regra de negócio

Desenvolver toda a lógica pela qual o sistema será submetido.

- Validações de e-mails, senhas.

- Desenvolver uma boa segurança para o usuário (Spring Security).

- Desenvolver todos os testes (JUnit)

Quaisquer dúvidas, abrir uma nova issue.

**Comment by Marzeu** [comment]
Segurança implementada com Spring Security + token jwt.
Validação dos campos.

Agora o coordenador(usuário) deve logar com e-mail e senha.
A senha é gravada no banco encriptada.
Token com validade de 30 min.

**Comment by rrenans** [comment]
Ótimo Marza, vou fechar essa Issue.
